/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categoryExplained`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `/auth/recoverPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verifyEmail`; params?: Router.UnknownInputParams; } | { pathname: `/register/createRegister`; params?: Router.UnknownInputParams; } | { pathname: `/register/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/categoryExplained`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/map`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/createAccount`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/recoverPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/verifyEmail`; params?: Router.UnknownOutputParams; } | { pathname: `/register/createRegister`; params?: Router.UnknownOutputParams; } | { pathname: `/register/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/categoryExplained${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/createAccount${`?${string}` | `#${string}` | ''}` | `/auth/recoverPassword${`?${string}` | `#${string}` | ''}` | `/auth/verifyEmail${`?${string}` | `#${string}` | ''}` | `/register/createRegister${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/categoryExplained`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/map`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/createAccount`; params?: Router.UnknownInputParams; } | { pathname: `/auth/recoverPassword`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verifyEmail`; params?: Router.UnknownInputParams; } | { pathname: `/register/createRegister`; params?: Router.UnknownInputParams; } | `/register/${Router.SingleRoutePart<T>}` | { pathname: `/register/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
